/* ©2019-2020 Elder Research, Inc. All rights reserved. */
package com.compassion.commons.utf;

// CHECKSTYLE:OFF
public interface UnicodeCyrillic {
    /** Ѐ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_IE_WITH_GRAVE = '\u0400';
    /** Ё of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_IO = '\u0401';
    /** Ђ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_DJE = '\u0402';
    /** Ѓ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_GJE = '\u0403';
    /** Є of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_UKRAINIAN_IE = '\u0404';
    /** Ѕ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_DZE = '\u0405';
    /** І of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_BYELORUSSIAN_UKRAINIAN_I = '\u0406';
    /** Ї of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_YI = '\u0407';
    /** Ј of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_JE = '\u0408';
    /** Љ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_LJE = '\u0409';
    /** Њ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_NJE = '\u040A';
    /** Ћ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_TSHE = '\u040B';
    /** Ќ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_KJE = '\u040C';
    /** Ѝ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_I_WITH_GRAVE = '\u040D';
    /** Ў of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_SHORT_U = '\u040E';
    /** Џ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_DZHE = '\u040F';
    /** А of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_A = '\u0410';
    /** Б of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_BE = '\u0411';
    /** В of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_VE = '\u0412';
    /** Г of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_GHE = '\u0413';
    /** Д of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_DE = '\u0414';
    /** Е of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_IE = '\u0415';
    /** Ж of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_ZHE = '\u0416';
    /** З of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_ZE = '\u0417';
    /** И of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_I = '\u0418';
    /** Й of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_SHORT_I = '\u0419';
    /** К of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_KA = '\u041A';
    /** Л of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_EL = '\u041B';
    /** М of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_EM = '\u041C';
    /** Н of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_EN = '\u041D';
    /** О of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_O = '\u041E';
    /** П of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_PE = '\u041F';
    /** Р of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_ER = '\u0420';
    /** С of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_ES = '\u0421';
    /** Т of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_TE = '\u0422';
    /** У of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_U = '\u0423';
    /** Ф of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_EF = '\u0424';
    /** Х of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_HA = '\u0425';
    /** Ц of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_TSE = '\u0426';
    /** Ч of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_CHE = '\u0427';
    /** Ш of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_SHA = '\u0428';
    /** Щ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_SHCHA = '\u0429';
    /** Ъ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_HARD_SIGN = '\u042A';
    /** Ы of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_YERU = '\u042B';
    /** Ь of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_SOFT_SIGN = '\u042C';
    /** Э of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_E = '\u042D';
    /** Ю of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_YU = '\u042E';
    /** Я of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_YA = '\u042F';
    /** а of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_A = '\u0430';
    /** б of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_BE = '\u0431';
    /** в of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_VE = '\u0432';
    /** г of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_GHE = '\u0433';
    /** д of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_DE = '\u0434';
    /** е of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_IE = '\u0435';
    /** ж of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_ZHE = '\u0436';
    /** з of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_ZE = '\u0437';
    /** и of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_I = '\u0438';
    /** й of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_SHORT_I = '\u0439';
    /** к of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_KA = '\u043A';
    /** л of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_EL = '\u043B';
    /** м of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_EM = '\u043C';
    /** н of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_EN = '\u043D';
    /** о of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_O = '\u043E';
    /** п of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_PE = '\u043F';
    /** р of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_ER = '\u0440';
    /** с of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_ES = '\u0441';
    /** т of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_TE = '\u0442';
    /** у of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_U = '\u0443';
    /** ф of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_EF = '\u0444';
    /** х of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_HA = '\u0445';
    /** ц of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_TSE = '\u0446';
    /** ч of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_CHE = '\u0447';
    /** ш of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_SHA = '\u0448';
    /** щ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_SHCHA = '\u0449';
    /** ъ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_HARD_SIGN = '\u044A';
    /** ы of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_YERU = '\u044B';
    /** ь of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_SOFT_SIGN = '\u044C';
    /** э of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_E = '\u044D';
    /** ю of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_YU = '\u044E';
    /** я of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_YA = '\u044F';
    /** ѐ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_IE_WITH_GRAVE = '\u0450';
    /** ё of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_IO = '\u0451';
    /** ђ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_DJE = '\u0452';
    /** ѓ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_GJE = '\u0453';
    /** є of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_UKRAINIAN_IE = '\u0454';
    /** ѕ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_DZE = '\u0455';
    /** і of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_BYELORUSSIAN_UKRAINIAN_I = '\u0456';
    /** ї of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_YI = '\u0457';
    /** ј of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_JE = '\u0458';
    /** љ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_LJE = '\u0459';
    /** њ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_NJE = '\u045A';
    /** ћ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_TSHE = '\u045B';
    /** ќ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_KJE = '\u045C';
    /** ѝ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_I_WITH_GRAVE = '\u045D';
    /** ў of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_SHORT_U = '\u045E';
    /** џ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_DZHE = '\u045F';
    /** Ѡ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_OMEGA = '\u0460';
    /** ѡ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_OMEGA = '\u0461';
    /** Ѣ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_YAT = '\u0462';
    /** ѣ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_YAT = '\u0463';
    /** Ѥ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_IOTIFIED_E = '\u0464';
    /** ѥ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_IOTIFIED_E = '\u0465';
    /** Ѧ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_LITTLE_YUS = '\u0466';
    /** ѧ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_LITTLE_YUS = '\u0467';
    /** Ѩ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_IOTIFIED_LITTLE_YUS = '\u0468';
    /** ѩ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_IOTIFIED_LITTLE_YUS = '\u0469';
    /** Ѫ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_BIG_YUS = '\u046A';
    /** ѫ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_BIG_YUS = '\u046B';
    /** Ѭ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_IOTIFIED_BIG_YUS = '\u046C';
    /** ѭ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_IOTIFIED_BIG_YUS = '\u046D';
    /** Ѯ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_KSI = '\u046E';
    /** ѯ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_KSI = '\u046F';
    /** Ѱ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_PSI = '\u0470';
    /** ѱ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_PSI = '\u0471';
    /** Ѳ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_FITA = '\u0472';
    /** ѳ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_FITA = '\u0473';
    /** Ѵ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_IZHITSA = '\u0474';
    /** ѵ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_IZHITSA = '\u0475';
    /** Ѷ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_IZHITSA_WITH_DOUBLE_GRAVE_ACCENT = '\u0476';
    /** ѷ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_IZHITSA_WITH_DOUBLE_GRAVE_ACCENT = '\u0477';
    /** Ѹ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_UK = '\u0478';
    /** ѹ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_UK = '\u0479';
    /** Ѻ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_ROUND_OMEGA = '\u047A';
    /** ѻ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_ROUND_OMEGA = '\u047B';
    /** Ѽ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_OMEGA_WITH_TITLO = '\u047C';
    /** ѽ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_OMEGA_WITH_TITLO = '\u047D';
    /** Ѿ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_OT = '\u047E';
    /** ѿ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_OT = '\u047F';
    /** Ҁ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_KOPPA = '\u0480';
    /** ҁ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_KOPPA = '\u0481';
    /** ҂ of type OTHER_SYMBOL */
    char CYRILLIC_THOUSANDS_SIGN = '\u0482';
    /** Ҋ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_SHORT_I_WITH_TAIL = '\u048A';
    /** ҋ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_SHORT_I_WITH_TAIL = '\u048B';
    /** Ҍ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_SEMISOFT_SIGN = '\u048C';
    /** ҍ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_SEMISOFT_SIGN = '\u048D';
    /** Ҏ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_ER_WITH_TICK = '\u048E';
    /** ҏ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_ER_WITH_TICK = '\u048F';
    /** Ґ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_GHE_WITH_UPTURN = '\u0490';
    /** ґ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_GHE_WITH_UPTURN = '\u0491';
    /** Ғ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_GHE_WITH_STROKE = '\u0492';
    /** ғ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_GHE_WITH_STROKE = '\u0493';
    /** Ҕ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_GHE_WITH_MIDDLE_HOOK = '\u0494';
    /** ҕ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_GHE_WITH_MIDDLE_HOOK = '\u0495';
    /** Җ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_ZHE_WITH_DESCENDER = '\u0496';
    /** җ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_ZHE_WITH_DESCENDER = '\u0497';
    /** Ҙ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_ZE_WITH_DESCENDER = '\u0498';
    /** ҙ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_ZE_WITH_DESCENDER = '\u0499';
    /** Қ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_KA_WITH_DESCENDER = '\u049A';
    /** қ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_KA_WITH_DESCENDER = '\u049B';
    /** Ҝ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_KA_WITH_VERTICAL_STROKE = '\u049C';
    /** ҝ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_KA_WITH_VERTICAL_STROKE = '\u049D';
    /** Ҟ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_KA_WITH_STROKE = '\u049E';
    /** ҟ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_KA_WITH_STROKE = '\u049F';
    /** Ҡ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_BASHKIR_KA = '\u04A0';
    /** ҡ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_BASHKIR_KA = '\u04A1';
    /** Ң of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_EN_WITH_DESCENDER = '\u04A2';
    /** ң of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_EN_WITH_DESCENDER = '\u04A3';
    /** Ҥ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LIGATURE_EN_GHE = '\u04A4';
    /** ҥ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LIGATURE_EN_GHE = '\u04A5';
    /** Ҧ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_PE_WITH_MIDDLE_HOOK = '\u04A6';
    /** ҧ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_PE_WITH_MIDDLE_HOOK = '\u04A7';
    /** Ҩ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_ABKHASIAN_HA = '\u04A8';
    /** ҩ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_ABKHASIAN_HA = '\u04A9';
    /** Ҫ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_ES_WITH_DESCENDER = '\u04AA';
    /** ҫ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_ES_WITH_DESCENDER = '\u04AB';
    /** Ҭ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_TE_WITH_DESCENDER = '\u04AC';
    /** ҭ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_TE_WITH_DESCENDER = '\u04AD';
    /** Ү of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_STRAIGHT_U = '\u04AE';
    /** ү of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_STRAIGHT_U = '\u04AF';
    /** Ұ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_STRAIGHT_U_WITH_STROKE = '\u04B0';
    /** ұ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_STRAIGHT_U_WITH_STROKE = '\u04B1';
    /** Ҳ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_HA_WITH_DESCENDER = '\u04B2';
    /** ҳ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_HA_WITH_DESCENDER = '\u04B3';
    /** Ҵ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LIGATURE_TE_TSE = '\u04B4';
    /** ҵ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LIGATURE_TE_TSE = '\u04B5';
    /** Ҷ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_CHE_WITH_DESCENDER = '\u04B6';
    /** ҷ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_CHE_WITH_DESCENDER = '\u04B7';
    /** Ҹ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_CHE_WITH_VERTICAL_STROKE = '\u04B8';
    /** ҹ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_CHE_WITH_VERTICAL_STROKE = '\u04B9';
    /** Һ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_SHHA = '\u04BA';
    /** һ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_SHHA = '\u04BB';
    /** Ҽ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_ABKHASIAN_CHE = '\u04BC';
    /** ҽ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_ABKHASIAN_CHE = '\u04BD';
    /** Ҿ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_ABKHASIAN_CHE_WITH_DESCENDER = '\u04BE';
    /** ҿ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_ABKHASIAN_CHE_WITH_DESCENDER = '\u04BF';
    /** Ӏ of type UPPERCASE_LETTER */
    char CYRILLIC_LETTER_PALOCHKA = '\u04C0';
    /** Ӂ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_ZHE_WITH_BREVE = '\u04C1';
    /** ӂ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_ZHE_WITH_BREVE = '\u04C2';
    /** Ӄ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_KA_WITH_HOOK = '\u04C3';
    /** ӄ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_KA_WITH_HOOK = '\u04C4';
    /** Ӆ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_EL_WITH_TAIL = '\u04C5';
    /** ӆ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_EL_WITH_TAIL = '\u04C6';
    /** Ӈ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_EN_WITH_HOOK = '\u04C7';
    /** ӈ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_EN_WITH_HOOK = '\u04C8';
    /** Ӊ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_EN_WITH_TAIL = '\u04C9';
    /** ӊ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_EN_WITH_TAIL = '\u04CA';
    /** Ӌ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_KHAKASSIAN_CHE = '\u04CB';
    /** ӌ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_KHAKASSIAN_CHE = '\u04CC';
    /** Ӎ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_EM_WITH_TAIL = '\u04CD';
    /** ӎ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_EM_WITH_TAIL = '\u04CE';
    /** ӏ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_PALOCHKA = '\u04CF';
    /** Ӑ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_A_WITH_BREVE = '\u04D0';
    /** ӑ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_A_WITH_BREVE = '\u04D1';
    /** Ӓ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_A_WITH_DIAERESIS = '\u04D2';
    /** ӓ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_A_WITH_DIAERESIS = '\u04D3';
    /** Ӕ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LIGATURE_A_IE = '\u04D4';
    /** ӕ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LIGATURE_A_IE = '\u04D5';
    /** Ӗ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_IE_WITH_BREVE = '\u04D6';
    /** ӗ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_IE_WITH_BREVE = '\u04D7';
    /** Ә of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_SCHWA = '\u04D8';
    /** ә of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_SCHWA = '\u04D9';
    /** Ӛ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_SCHWA_WITH_DIAERESIS = '\u04DA';
    /** ӛ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_SCHWA_WITH_DIAERESIS = '\u04DB';
    /** Ӝ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_ZHE_WITH_DIAERESIS = '\u04DC';
    /** ӝ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_ZHE_WITH_DIAERESIS = '\u04DD';
    /** Ӟ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_ZE_WITH_DIAERESIS = '\u04DE';
    /** ӟ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_ZE_WITH_DIAERESIS = '\u04DF';
    /** Ӡ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_ABKHASIAN_DZE = '\u04E0';
    /** ӡ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_ABKHASIAN_DZE = '\u04E1';
    /** Ӣ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_I_WITH_MACRON = '\u04E2';
    /** ӣ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_I_WITH_MACRON = '\u04E3';
    /** Ӥ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_I_WITH_DIAERESIS = '\u04E4';
    /** ӥ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_I_WITH_DIAERESIS = '\u04E5';
    /** Ӧ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_O_WITH_DIAERESIS = '\u04E6';
    /** ӧ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_O_WITH_DIAERESIS = '\u04E7';
    /** Ө of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_BARRED_O = '\u04E8';
    /** ө of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_BARRED_O = '\u04E9';
    /** Ӫ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_BARRED_O_WITH_DIAERESIS = '\u04EA';
    /** ӫ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_BARRED_O_WITH_DIAERESIS = '\u04EB';
    /** Ӭ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_E_WITH_DIAERESIS = '\u04EC';
    /** ӭ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_E_WITH_DIAERESIS = '\u04ED';
    /** Ӯ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_U_WITH_MACRON = '\u04EE';
    /** ӯ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_U_WITH_MACRON = '\u04EF';
    /** Ӱ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_U_WITH_DIAERESIS = '\u04F0';
    /** ӱ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_U_WITH_DIAERESIS = '\u04F1';
    /** Ӳ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_U_WITH_DOUBLE_ACUTE = '\u04F2';
    /** ӳ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_U_WITH_DOUBLE_ACUTE = '\u04F3';
    /** Ӵ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_CHE_WITH_DIAERESIS = '\u04F4';
    /** ӵ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_CHE_WITH_DIAERESIS = '\u04F5';
    /** Ӷ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_GHE_WITH_DESCENDER = '\u04F6';
    /** ӷ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_GHE_WITH_DESCENDER = '\u04F7';
    /** Ӹ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_YERU_WITH_DIAERESIS = '\u04F8';
    /** ӹ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_YERU_WITH_DIAERESIS = '\u04F9';
    /** Ӻ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_GHE_WITH_STROKE_AND_HOOK = '\u04FA';
    /** ӻ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_GHE_WITH_STROKE_AND_HOOK = '\u04FB';
    /** Ӽ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_HA_WITH_HOOK = '\u04FC';
    /** ӽ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_HA_WITH_HOOK = '\u04FD';
    /** Ӿ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_HA_WITH_STROKE = '\u04FE';
    /** ӿ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_HA_WITH_STROKE = '\u04FF';
    /** Ԁ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_KOMI_DE = '\u0500';
    /** ԁ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_KOMI_DE = '\u0501';
    /** Ԃ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_KOMI_DJE = '\u0502';
    /** ԃ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_KOMI_DJE = '\u0503';
    /** Ԅ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_KOMI_ZJE = '\u0504';
    /** ԅ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_KOMI_ZJE = '\u0505';
    /** Ԇ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_KOMI_DZJE = '\u0506';
    /** ԇ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_KOMI_DZJE = '\u0507';
    /** Ԉ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_KOMI_LJE = '\u0508';
    /** ԉ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_KOMI_LJE = '\u0509';
    /** Ԋ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_KOMI_NJE = '\u050A';
    /** ԋ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_KOMI_NJE = '\u050B';
    /** Ԍ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_KOMI_SJE = '\u050C';
    /** ԍ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_KOMI_SJE = '\u050D';
    /** Ԏ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_KOMI_TJE = '\u050E';
    /** ԏ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_KOMI_TJE = '\u050F';
    /** Ԑ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_REVERSED_ZE = '\u0510';
    /** ԑ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_REVERSED_ZE = '\u0511';
    /** Ԓ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_EL_WITH_HOOK = '\u0512';
    /** ԓ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_EL_WITH_HOOK = '\u0513';
    /** Ԕ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_LHA = '\u0514';
    /** ԕ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_LHA = '\u0515';
    /** Ԗ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_RHA = '\u0516';
    /** ԗ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_RHA = '\u0517';
    /** Ԙ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_YAE = '\u0518';
    /** ԙ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_YAE = '\u0519';
    /** Ԛ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_QA = '\u051A';
    /** ԛ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_QA = '\u051B';
    /** Ԝ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_WE = '\u051C';
    /** ԝ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_WE = '\u051D';
    /** Ԟ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_ALEUT_KA = '\u051E';
    /** ԟ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_ALEUT_KA = '\u051F';
    /** Ԡ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_EL_WITH_MIDDLE_HOOK = '\u0520';
    /** ԡ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_EL_WITH_MIDDLE_HOOK = '\u0521';
    /** Ԣ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_EN_WITH_MIDDLE_HOOK = '\u0522';
    /** ԣ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_EN_WITH_MIDDLE_HOOK = '\u0523';
    /** Ԥ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_PE_WITH_DESCENDER = '\u0524';
    /** ԥ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_PE_WITH_DESCENDER = '\u0525';
    /** Ԧ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_SHHA_WITH_DESCENDER = '\u0526';
    /** ԧ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_SHHA_WITH_DESCENDER = '\u0527';
    /** ᴫ of type LOWERCASE_LETTER */
    char CYRILLIC_LETTER_SMALL_CAPITAL_EL = '\u1D2B';
    /** Ꙁ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_ZEMLYA = '\uA640';
    /** ꙁ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_ZEMLYA = '\uA641';
    /** Ꙃ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_DZELO = '\uA642';
    /** ꙃ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_DZELO = '\uA643';
    /** Ꙅ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_REVERSED_DZE = '\uA644';
    /** ꙅ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_REVERSED_DZE = '\uA645';
    /** Ꙇ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_IOTA = '\uA646';
    /** ꙇ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_IOTA = '\uA647';
    /** Ꙉ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_DJERV = '\uA648';
    /** ꙉ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_DJERV = '\uA649';
    /** Ꙋ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_MONOGRAPH_UK = '\uA64A';
    /** ꙋ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_MONOGRAPH_UK = '\uA64B';
    /** Ꙍ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_BROAD_OMEGA = '\uA64C';
    /** ꙍ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_BROAD_OMEGA = '\uA64D';
    /** Ꙏ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_NEUTRAL_YER = '\uA64E';
    /** ꙏ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_NEUTRAL_YER = '\uA64F';
    /** Ꙑ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_YERU_WITH_BACK_YER = '\uA650';
    /** ꙑ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_YERU_WITH_BACK_YER = '\uA651';
    /** Ꙓ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_IOTIFIED_YAT = '\uA652';
    /** ꙓ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_IOTIFIED_YAT = '\uA653';
    /** Ꙕ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_REVERSED_YU = '\uA654';
    /** ꙕ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_REVERSED_YU = '\uA655';
    /** Ꙗ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_IOTIFIED_A = '\uA656';
    /** ꙗ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_IOTIFIED_A = '\uA657';
    /** Ꙙ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_CLOSED_LITTLE_YUS = '\uA658';
    /** ꙙ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_CLOSED_LITTLE_YUS = '\uA659';
    /** Ꙛ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_BLENDED_YUS = '\uA65A';
    /** ꙛ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_BLENDED_YUS = '\uA65B';
    /** Ꙝ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_IOTIFIED_CLOSED_LITTLE_YUS = '\uA65C';
    /** ꙝ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_IOTIFIED_CLOSED_LITTLE_YUS = '\uA65D';
    /** Ꙟ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_YN = '\uA65E';
    /** ꙟ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_YN = '\uA65F';
    /** Ꙡ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_REVERSED_TSE = '\uA660';
    /** ꙡ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_REVERSED_TSE = '\uA661';
    /** Ꙣ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_SOFT_DE = '\uA662';
    /** ꙣ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_SOFT_DE = '\uA663';
    /** Ꙥ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_SOFT_EL = '\uA664';
    /** ꙥ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_SOFT_EL = '\uA665';
    /** Ꙧ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_SOFT_EM = '\uA666';
    /** ꙧ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_SOFT_EM = '\uA667';
    /** Ꙩ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_MONOCULAR_O = '\uA668';
    /** ꙩ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_MONOCULAR_O = '\uA669';
    /** Ꙫ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_BINOCULAR_O = '\uA66A';
    /** ꙫ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_BINOCULAR_O = '\uA66B';
    /** Ꙭ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_DOUBLE_MONOCULAR_O = '\uA66C';
    /** ꙭ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_DOUBLE_MONOCULAR_O = '\uA66D';
    /** ꙮ of type OTHER_LETTER */
    char CYRILLIC_LETTER_MULTIOCULAR_O = '\uA66E';
    /** ꙾ of type OTHER_PUNCTUATION */
    char CYRILLIC_KAVYKA = '\uA67E';
    /** ꙿ of type MODIFIER_LETTER */
    char CYRILLIC_PAYEROK = '\uA67F';
    /** Ꚁ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_DWE = '\uA680';
    /** ꚁ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_DWE = '\uA681';
    /** Ꚃ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_DZWE = '\uA682';
    /** ꚃ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_DZWE = '\uA683';
    /** Ꚅ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_ZHWE = '\uA684';
    /** ꚅ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_ZHWE = '\uA685';
    /** Ꚇ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_CCHE = '\uA686';
    /** ꚇ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_CCHE = '\uA687';
    /** Ꚉ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_DZZE = '\uA688';
    /** ꚉ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_DZZE = '\uA689';
    /** Ꚋ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_TE_WITH_MIDDLE_HOOK = '\uA68A';
    /** ꚋ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_TE_WITH_MIDDLE_HOOK = '\uA68B';
    /** Ꚍ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_TWE = '\uA68C';
    /** ꚍ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_TWE = '\uA68D';
    /** Ꚏ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_TSWE = '\uA68E';
    /** ꚏ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_TSWE = '\uA68F';
    /** Ꚑ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_TSSE = '\uA690';
    /** ꚑ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_TSSE = '\uA691';
    /** Ꚓ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_TCHE = '\uA692';
    /** ꚓ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_TCHE = '\uA693';
    /** Ꚕ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_HWE = '\uA694';
    /** ꚕ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_HWE = '\uA695';
    /** Ꚗ of type UPPERCASE_LETTER */
    char CYRILLIC_CAPITAL_LETTER_SHWE = '\uA696';
    /** ꚗ of type LOWERCASE_LETTER */
    char CYRILLIC_SMALL_LETTER_SHWE = '\uA697';
}
// CHECKSTYLE:ON
